Ensure run-tests indicates failure if LDAP cannot be reset

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -1,8 +1,12 @@
 #!/bin/sh
 python tests/reset_ldap.py
-if [ $? -ne 0 ]
+
+ret=$?
+
+if [ $ret -ne 0 ]
 then
-	echo 'Failed to reset LDAP' $?
+	echo 'Failed to reset LDAP'
+	exit $ret
 else
 	exec nosetests -d $*
 fi
